# Generated by Django 4.1.2 on 2022-10-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', help_text='Заголовок', max_length=255, verbose_name='Заголовок')),
                ('photo', models.ImageField(default=' ', upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo2', models.ImageField(blank=True, default=' ', upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo3', models.ImageField(blank=True, default=' ', upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo4', models.ImageField(blank=True, default=' ', upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo5', models.ImageField(blank=True, default=' ', upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('text', models.TextField(default=' ', help_text='Содержание книги', verbose_name='Содержание книги')),
                ('responsible', models.CharField(default=' ', help_text='Ответственный', max_length=255, verbose_name='Ответственный')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'AllPosts',
                'verbose_name_plural': 'Посты на странице',
                'ordering': ['time_create'],
            },
        ),
    ]
